# Generated by Django 5.2.3 on 2025-06-30 Ы14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliographicSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='article_url',
            new_name='url',
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('regional', 'Региональная'), ('national', 'Всероссийская'), ('international_part', 'С международным участием'), ('international', 'Международная')], max_length=20, verbose_name='Статус')),
                ('publications', models.ManyToManyField(blank=True, related_name='conferences', to='BibliographicSystem.publication', verbose_name='Публикации')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Название (англ)')),
                ('quartile', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('N/A', 'Не определен')], default='N/A', max_length=3, verbose_name='Квартиль')),
                ('whitelist_level', models.CharField(choices=[('1', 'Уровень 1'), ('2', 'Уровень 2'), ('3', 'Уровень 3'), ('4', 'Уровень 4'), ('none', 'Не в списке')], default='none', max_length=10, verbose_name='Уровень белого списка')),
                ('website', models.URLField(blank=True, verbose_name='Сайт журнала')),
                ('publications', models.ManyToManyField(blank=True, related_name='journals', to='BibliographicSystem.publication', verbose_name='Публикации')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ['title_en'],
            },
        ),
    ]
