# Generated by Django 5.2.3 on 2025-08-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibliographicSystem', '0003_mymodel_journal_title_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['title'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='journal_or_conference',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title_ru',
        ),
    ]
