# Generated by Django 5.2.3 on 2025-08-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibliographicSystem', '0004_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['title'], 'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='title_ru',
        ),
    ]
