# Generated by Django 5.2.3 on 2025-06-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliographicSystem', '0002_rename_article_url_publication_url_conference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (рус)'),
        ),
    ]
